spring.application.name=lunchies

# Docker Compose
spring.docker.compose.file=backend/compose.yaml

# Flyway migration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Data cleanup
cleanup.retention-days=90
cleanup.cron=0 0 3 * * *

# Slack
slack.bot.token=${SLACK_BOT_TOKEN}
slack.signing.secret=${SLACK_SIGNING_SECRET}
slack.channel.id=${SLACK_CHANNEL_ID}
super.admin.slack.id=${SUPER_ADMIN_SLACK_ID}
